import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./preline/preline";
import { AuthProvider } from "@propelauth/nextjs/client";
import { getUser } from "@propelauth/nextjs/server/app-router";
import LoginAndSignup from "../components/auth/login_and_signup";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  if (user) {
    return (
      <html lang="en">
        <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL!}>
          <PrelineScript />
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL!}>
          <PrelineScript />
          <body className={inter.className}>
            <LoginAndSignup />
          </body>
        </AuthProvider>
      </html>
    );
  }
}
